### ISSUE TITLE
Loading section of the checker is failing to handle qc sample stationid 0000

### ISSUE THREAD

**Issue by pdsmith** [SCCWRP/bight23checker#11]
The qc sample stationid 0000 passes core checks when matched against lu_station lookup list, but fails on the same lookup list when the data is actually loaded to the database - it is rounding the number 0000 to 0 instead of retaining the data type as text and value as 0000.

Error:
Checker application came across an error
(psycopg2.errors.ForeignKeyViolation) insert or update on table "tbl_toxresults" violates foreign key constraint "tbl_toxresults_stationid_fkey"
DETAIL:  Key (stationid)=(0) is not present in table "lu_station".

Potential fix:
Same portion of code that tells the checker to handle each data type so it matches the database schema (used in checks) needs to get used prior to data loading.

Wrong fix: Don't use ceriodaphnia checker fix for the problem. We do not want the values truncated to 0.

**Comment by duynguyen2019** [comment]
The issue was the SQL generated by the code did not wrap the 0000 value in single quotes since it mistakenly thought the 0000 is numeric.

We fixed it by wrapping the single quotes for all values except sde.next_ functions.

I tested it and checker was able to load the file.
