### ISSUE TITLE
Mismatch function fails when column datatypes differ

### ISSUE THREAD

**Issue by r7butler** [SCCWRP/bight23checker#17]
This bug was discovered in the microplastics checker. In a logic check, one column "labbatch" had a value "batch1" while another dataframe's labbatch column had simply the number 1

I got an error which said "You are trying to merge on object and int64 columns"

This bug is fixed in the microplastics checker and needs to be applied to the other checker applications.

its the function called "mismatch" in proj/custom/functions.py

**Comment by r7butler** [comment]
@duynguyen2019 @pdsmith  just a heads up

**Comment by duynguyen2019** [comment]
Thank you, I'll update the mismatch function for EMPA and SMC Checker

**Comment by duynguyen2019** [comment]
It would be good if we could make this a Lambda function

**Comment by r7butler** [comment]
fixed with commit 275eb40
